M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu23.04.1} date Di 23 Mai 2023 16:13:52 CEST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-23T16:13:52+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu23.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
%
G90
G05
T1
X73.31Y-84.268
X79.09Y-84.268
T0
M30
